# Site settings
title: GhettoSpace - Crossroads
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/ghettospace/" # the subpath of your site, e.g. /blog/
url: "http://saricden.github.io"
github_username:  saricden
twitter_username: saricden
facebook_username: saricden
tumblr_username: saricden


patreon: https://www.patreon.com

game_version: 0.1
game_link: /v/0.1
cover_art: https://images.unsplash.com/photo-1446776858070-70c3d5ed6758?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=9bbb8a4b7e9b0107fdb0fe52d0dbcaff
game_icon: https://33.media.tumblr.com/avatar_097115c9cd65_128.png

# Build settings
markdown: kramdown
