# Site settings
title: GhettoSpace - Crossroads
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/ghettospace/" # the subpath of your site, e.g. /blog/
url: "http://saricden.github.io
github_username:  saricden
twitter_username: saricden
facebook_username: saricden
tumblr_username: saricden


patreon: https://www.patreon.com

game_version: 0.1
game_link: /v/0.1
cover_art: http://www.this-is-cool.co.uk/wp-content/gallery/jaime-jones/jaime-jones-video-game-art.jpg

# Build settings
markdown: kramdown
